import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '@/styles/variables.css'
import '@/styles/globals.css'

const openSans = Open_Sans({
    variable: '--font-family-base',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Alura Cases',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
    return (
        <html lang="pt-br">
            <body className={openSans.variable}>
                <div className="layout-principal">{children}</div>
            </body>
        </html>
    )
}
